---
extends:
  - 'plugin:astro/recommended'
  - 'plugin:jsx-a11y/recommended'
  - 'prettier'
overrides:
  # Define the configuration for `.astro` file.
  - files:
      - '*.astro'
    plugins:
      - 'astro'
    env:
      # #nables global variables available in Astro components.
      node: true
      astro/astro: true
      es2020: true
    # Allows Astro components to be parsed.
    parser: 'astro-eslint-parser'
    # Parse the script in `.astro` as TypeScript by adding the following configuration.
    parserOptions:
      parser: '@typescript-eslint/parser'
      extraFileExtensions:
        - '.astro'
      sourceType: 'module'
    rules:
      astro/no-conflict-set-directives: 'error'
      astro/no-unused-define-vars-in-style: 'error'

  # Define the configuration for `<script>` tag.
  # Script in `<script>` is assigned a virtual file name with the `.js` extension.
  - files:
      - '**/*.astro/*.js'
      - '*.astro/*.js'
    env:
      browser: true
      es2020: true
    parserOptions:
      sourceType: 'module'
    rules:
      # If you are using 'prettier/prettier' rule,
      # you don't need to format inside <script> as it will be formatted as a `.astro` file.
      prettier/prettier: 'off'
