---
printWidth: 125
trailingComma: 'es5'
tabWidth: 4
useTabs: false
semi: true
singleQuote: true
endOfLine: lf

plugins:
    - 'prettier-plugin-astro'
    - 'prettier-plugin-tailwindcss'
pluginSearchDirs: false

overrides:
    - files: '*.astro'
      options:
          parser: 'astro'
    - files: '*.yaml'
      options:
          tabWidth: 2
