---
name: build-and-deploy

on:
  pull_request: ~
  workflow_dispatch: ~

run-name: |-
  ${{ github.event_name == 'workflow_dispatch' && 'Manual' || 'Automatic' }} build and deploy for ${{ github.ref == 'refs/heads/main' && 'Production' || 'Preview' }} environment

jobs:
  update:
    timeout-minutes: 5
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1

      - name: Resolve Dependencies
        run: bun install --frozen-lockfile
        env:
          HUSKY: 0

      - name: Build
        run: bun run build

      - name: Publish to Cloudflare Pages
        id: deploy
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
          projectName: nacl30d
          directory: dist
          # gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          wranglerVersion: '3'
