---
name: checks

on:
  pull_request: ~
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v5
        with:
          node-version-file: .tool-versions
          cache: 'pnpm'

      - name: Resolve Dependencies
        run: pnpm install --frozen-lockfile

      - name: Check code
        run: pnpm run check

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v5
        with:
          node-version-file: .tool-versions
          cache: 'pnpm'

      - name: Resolve Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run build
