---
name: checks

on:
  pull_request: ~
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - name: Resolve Dependencies
        run: pnpm install --frozen-lockfile
        env:
          HUSKY: 0

      - name: Check code
        run: pnpm run check

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - name: Resolve Dependencies
        run: pnpm install --frozen-lockfile
        env:
          HUSKY: 0

      - name: Build
        run: pnpm run build
