name: CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: oven-sh/setup-bun@v1

    - name: Resolve Dependencies
      run: bun install --frozen-lockfile
      env:
        HUSKY: 0

    - name: Check code
      run: bun run lint

    - name: Build
      run: bun run build
